# Boundary configuration for Linux 6.15 (EEVDF support)
# Based on Linux 5.10 configuration with EEVDF adaptations

version: "1.0"
kernel_version: "6.15"
architecture: "aarch64"

# Core scheduler source files
sources:
  - kernel/sched/core.c
  - kernel/sched/fair.c
  - kernel/sched/rt.c
  - kernel/sched/deadline.c
  - kernel/sched/idle.c
  - kernel/sched/stop_task.c
  - kernel/sched/cpudeadline.c
  - kernel/sched/cpupri.c
  - kernel/sched/topology.c
  - kernel/sched/debug.c
  - kernel/sched/stats.c
  - kernel/sched/wait.c
  - kernel/sched/completion.c
  - kernel/sched/swait.c
  - kernel/sched/wait_bit.c

# Main scheduler interface functions
interfaces:
  - schedule
  - schedule_idle
  - schedule_preempt_disabled
  - schedule_timeout
  - io_schedule
  - io_schedule_timeout
  - sched_setscheduler
  - sched_setscheduler_nocheck
  - sched_setattr
  - sched_setattr_nocheck
  - sched_getattr
  - sched_get_priority_max
  - sched_get_priority_min
  - yield
  - yield_to
  - sched_fork
  - wake_up_new_task
  - set_user_nice
  - set_cpus_allowed_ptr

# EEVDF specific features
eevdf:
  enabled: true
  features:
    - virtual_deadline
    - eligibility_check
    - lag_based_placement

# Scheduler features to expose
sched_features:
  - GENTLE_FAIR_SLEEPERS
  - START_DEBIT
  - NEXT_BUDDY
  - LAST_BUDDY
  - CACHE_HOT_BUDDY
  - WAKEUP_PREEMPTION
  - HRTICK
  - DOUBLE_TICK
  - NONTASK_CAPACITY
  - TTWU_QUEUE
  - SIS_AVG_CPU
  - SIS_PROP
  - WARN_DOUBLE_CLOCK
  - RT_PUSH_IPI
  - RT_RUNTIME_SHARE
  - LB_MIN
  - ATTACH_AGE_LOAD
  - WA_IDLE
  - WA_WEIGHT
  - WA_BIAS
  - UTIL_EST

# Critical data structures for state rebuild
critical_data:
  - rq
  - cfs_rq
  - rt_rq
  - dl_rq
  - sched_entity
  - sched_class
  - task_group
  - cfs_bandwidth

# Shared data (between kernel and module)
shared_data:
  - sysctl_sched_latency
  - sysctl_sched_min_granularity
  - sysctl_sched_wakeup_granularity
  - sysctl_sched_child_runs_first
  - sysctl_sched_nr_migrate
  - sysctl_sched_time_avg
  - sysctl_sched_shares_window
  - sysctl_sched_tunable_scaling

# Private data (module only)
private_data:
  - scheduler_statistics
  - debug_counters
  - module_parameters

# Symbols to export from module
exports:
  - scheduler_tick
  - update_rq_clock
  - scheduler_ipi
  - resched_curr
  - check_preempt_curr
  - task_curr
  - cpu_curr

# Notes for 6.15 specific changes
notes: |
  Linux 6.15 introduces EEVDF scheduler which replaces some CFS internals.
  Key differences from 5.10:
  - Virtual deadline based scheduling instead of pure vruntime
  - Eligibility checking for task selection
  - Lag-based placement for improved latency
  - Modified pick_next_task logic
  
  When adapting patches:
  - Update vruntime calculations to account for EEVDF
  - Modify deadline calculation functions
  - Adjust entity selection logic
